### ISSUE TITLE
Wrong MTEPS calculation. Should use the edges in the connected component.

### ISSUE THREAD

**Issue by hehelego** [chibinz/ParallelBFS#1]
https://github.com/chibinz/ParallelBFS/blob/4c7f25b9788385617a4c368e23147ffe12c80ade/src/main.c#L50  

```cpp
  double edges = (double)(adj->nz) / 1e6;
  printf("%-16s%-16.4f%-16.4f%-16.4f\n", name, edges / mean,
         edges * stddev / mean, mean);
```

Perhaps, assuming that the graph is connected is invalid.

**Comment by chibinz** [comment]
Yeah, you're definitely right! I've chatted with the professor on this issue. He said it's fine since this is just a course project.

My main concern is that counting the number of nodes in the connected component along with bfs may degrade performance. Assuming that you setup a global atomic variable to record the number of nodes, there will be a lot of contention if you modify it very frequently. 

I've been very busy with other stuff recently. So if you have any idea on how to do this efficiently with little overhead, feel free to submit a pull request. I'll be more than willing to merge it into master.
